kind: pipeline
type: docker
name: test

steps:
  - name: Test Go
    image: golang:1.25
    commands:
      - apt-get update && apt-get install -y xz-utils
      - curl https://qlty.sh | sh
      - make cover
      - ~/.qlty/bin/qlty coverage publish c.out --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_7zcAFXn6fkui7G14

  - name: Test Makefile
    image: cytopia/checkmake:latest
    commands:
      - checkmake Makefile
